# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'cineMAniac' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for cineMAniac
  pod 'ObjectMapper'
  pod 'Alamofire'
  pod 'AlamofireImage'
  pod 'SwiftyJSON'
  pod ‘TPKeyboardAvoiding’
  pod 'SVProgressHUD'

  target 'cineMAniacTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'cineMAniacUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
